### ISSUE TITLE
crash in resample_cython_demo

### ISSUE THREAD

**Issue by matthias-k** [nsf-ri-ubicv/sthor#14]
Hi,

I tried to compile sthor by running the makefile in `sthor/operation`. However, when make runs `python resample_cython_demo.py`, it crashes:

```
python resample_cython_demo.py
(256, 256, 96)
make: *** [resample] Illegal instruction (core dumped)
```

I use ubuntu 14.04 LTS with python 2.7.

**Comment by npinto** [comment]
Could you please try to remove some of the following flags:
https://github.com/nsf-ri-ubicv/sthor/blob/master/sthor/operation/setup.py#L30

**Comment by matthias-k** [comment]
Thank you a lot! removing `-msse4` made the demo run. I still have some problems with the top level setup.py but I hope I can figure them out myself.

Best,
  Matthias
